# Generated by Django 2.1 on 2019-04-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='buat_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=100)),
                ('gambar', models.FileField(null=True, upload_to='images')),
                ('nama', models.CharField(blank=True, max_length=300)),
                ('ttl', models.CharField(blank=True, max_length=300)),
                ('dojang', models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=300)),
                ('umur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabukawal', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Dari Sabuk')),
                ('sabukujian', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Ke Sabuk')),
                ('hasilujian', models.CharField(choices=[('LULUS', 'Lulus'), ('TIDAK LULUS', 'Tidak Lulus'), ('AKAN UJIAN', 'Akan Ujian')], max_length=100, null=True)),
                ('waktu', models.CharField(max_length=30)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='zwinkle.Collection')),
            ],
            options={
                'get_latest_by': 'hasilujian',
            },
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='konten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('isi', models.TextField()),
                ('author', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('gambar', models.FileField(null=True, upload_to='images')),
                ('isi', models.CharField(max_length=1000)),
                ('kategori', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Django Rest Framework', 'Django Rest Framework')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='zwinkle.Publication'),
        ),
    ]
