# Generated by Django 2.1 on 2019-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.CreateModel(
            name='buat_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='konten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('isi', models.TextField()),
                ('author', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Krida_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nama')),
                ('ttl', models.CharField(max_length=30)),
                ('dojang', models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=30)),
                ('umur', models.IntegerField()),
                ('view', models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Krida_model_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabukawal', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default='Putih', max_length=100, verbose_name='Dari Sabuk')),
                ('sabukujian', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default='Putih', max_length=100, verbose_name='Ke Sabuk')),
                ('hasilujian', models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default='-', max_length=100)),
                ('waktu', models.CharField(default='x', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('gambar', models.FileField(null=True, upload_to='images')),
                ('isi', models.CharField(max_length=1000)),
                ('kategori', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Django Rest Framework', 'Django Rest Framework')], default=1, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='krida_model',
            name='krida_models',
            field=models.ManyToManyField(to='zwinkle.Krida_model_detail'),
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='zwinkle.Publication'),
        ),
    ]
