# Generated by Django 2.1 on 2019-05-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='locations',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
