# Generated by Django 2.1 on 2019-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
