# Generated by Django 2.1 on 2018-11-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buatlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=15)),
                ('password', models.TextField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='konten',
        ),
    ]
