# Generated by Django 2.1 on 2019-03-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krida_model',
            name='dojang',
        ),
        migrations.RemoveField(
            model_name='krida_model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='krida_model',
            name='ttl',
        ),
        migrations.RemoveField(
            model_name='krida_model',
            name='umur',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='hasilujian',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='sabukawal',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='sabukujian',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='waktu',
        ),
        migrations.AddField(
            model_name='krida_model_detail',
            name='dojang',
            field=models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='krida_model_detail',
            name='name',
            field=models.CharField(default='risma', max_length=30, verbose_name='Nama'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krida_model_detail',
            name='ttl',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='krida_model_detail',
            name='umur',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='krida_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwinkle.krida_model_detail'),
        ),
    ]
