# Generated by Django 2.1 on 2018-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0002_auto_20181106_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='konten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('isi', models.TextField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='buatlogin',
        ),
    ]
