# Generated by Django 2.1 on 2019-05-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0002_auto_20190514_0316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
