# Generated by Django 2.1 on 2019-04-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0002_auto_20190410_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='tempat_lahir',
            new_name='ttl',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='filters',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='tanggal_lahir',
        ),
        migrations.AddField(
            model_name='collection',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
