# Generated by Django 2.1 on 2019-06-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0002_auto_20190619_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojang', models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='Krida', max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='dojang',
        ),
        migrations.AddField(
            model_name='collection',
            name='filters',
            field=models.CharField(choices=[('ON', 'ON')], default='OFF', max_length=300),
        ),
        migrations.AddField(
            model_name='collection',
            name='anggota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anggota_uti', to='zwinkle.Anggota'),
        ),
    ]
