# Generated by Django 2.1 on 2019-03-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0002_auto_20190320_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='krida_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asu', to='zwinkle.Krida_model_detail'),
        ),
    ]
