# Generated by Django 2.1 on 2019-03-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0003_auto_20190320_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krida_model',
            name='krida_models',
        ),
        migrations.AddField(
            model_name='krida_model',
            name='krida_models',
            field=models.ManyToManyField(to='zwinkle.Krida_model_detail'),
        ),
    ]
