# Generated by Django 2.1 on 2019-04-10 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0003_auto_20190410_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='ttl',
            new_name='tempat_lahir',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='note',
        ),
        migrations.AddField(
            model_name='collection',
            name='filters',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=300),
        ),
        migrations.AddField(
            model_name='collection',
            name='tanggal_lahir',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
