# Generated by Django 2.1 on 2019-03-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0004_auto_20190320_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model_detail',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='krida_model_detail',
            name='sabukawal',
            field=models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Dari Sabuk'),
        ),
        migrations.AlterField(
            model_name='krida_model_detail',
            name='sabukujian',
            field=models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Ke Sabuk'),
        ),
    ]
