# Generated by Django 2.1 on 2019-04-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0005_remove_collection_umur'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='id_reg',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
