# Generated by Django 2.1 on 2019-03-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0005_auto_20190320_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krida_model',
            name='krida_models',
        ),
        migrations.AddField(
            model_name='krida_model',
            name='krida_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='zwinkle.Krida_model_detail'),
        ),
    ]
