# Generated by Django 2.1.4 on 2018-12-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0005_auto_20181228_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='isi',
            field=models.TextField(max_length=1000),
        ),
    ]
