# Generated by Django 2.1 on 2019-03-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0006_auto_20190320_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='krida_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kridamodels', to='zwinkle.Krida_model_detail'),
        ),
        migrations.AlterModelTable(
            name='krida_model',
            table='krida_models',
        ),
        migrations.AlterModelTable(
            name='krida_model_detail',
            table='krida_models_details',
        ),
    ]
