# Generated by Django 2.1.4 on 2019-01-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0007_auto_20190101_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='kategori',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Django Rest Framework', 'Django Rest Framework')], default=1, max_length=100),
        ),
    ]
