# Generated by Django 2.1 on 2019-03-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0008_auto_20190329_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='krida_models',
        ),
        migrations.AddField(
            model_name='krida_model',
            name='krida_models',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kridamodels', to='zwinkle.Krida_model_detail'),
        ),
    ]
