# Generated by Django 2.1 on 2019-03-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0010_auto_20190329_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model_detail',
            name='waktu',
            field=models.CharField(max_length=30),
        ),
    ]
