# Generated by Django 2.1 on 2019-01-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0010_auto_20190110_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy_krida_model',
            name='umur',
            field=models.IntegerField(max_length=30),
        ),
    ]
