# Generated by Django 2.1 on 2019-03-30 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0011_auto_20190329_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Krida_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nama')),
                ('ttl', models.CharField(max_length=30)),
                ('dojang', models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=30)),
                ('umur', models.IntegerField()),
                ('view', models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Krida_master_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabukawal', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Dari Sabuk')),
                ('sabukujian', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Ke Sabuk')),
                ('hasilujian', models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default=None, max_length=100)),
                ('waktu', models.CharField(max_length=30)),
                ('krida_models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zwinkle.Krida_master')),
            ],
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='hasilujian',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='krida_models',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='sabukawal',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='sabukujian',
        ),
        migrations.RemoveField(
            model_name='krida_model_detail',
            name='waktu',
        ),
    ]
