# Generated by Django 2.1 on 2019-03-30 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0012_auto_20190330_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_master_detail',
            name='krida_models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krida_master_detail', to='zwinkle.Krida_master'),
        ),
    ]
