# Generated by Django 2.1 on 2019-01-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0012_auto_20190110_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='krida_model',
            old_name='nama',
            new_name='name',
        ),
    ]
