# Generated by Django 2.1 on 2019-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0013_auto_20190110_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('lulus', 'LULUS'), ('tidak lulus', 'TIDAK LULUS')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='krida_model',
            name='pembayaran',
            field=models.CharField(choices=[('150.000', '150.000'), ('300.000', '300.000'), ('LUNAS', 'LUNAS')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='umur',
            field=models.IntegerField(max_length=30),
        ),
    ]
