# Generated by Django 2.1 on 2019-03-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0013_auto_20190330_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=300)),
                ('ttl', models.CharField(blank=True, max_length=300)),
                ('dojang', models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=30)),
                ('umur', models.IntegerField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabukawal', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Dari Sabuk')),
                ('sabukujian', models.CharField(choices=[('Putih', 'Putih'), ('Kuning', 'Kuning'), ('Kuning Strip', 'Kuning Strip'), ('Hijau', 'Hijau'), ('Hijau Strip', 'Hijau Strip'), ('Biru', 'Biru'), ('Biru Strip', 'Biru Strip'), ('Merah', 'Merah'), ('Merah Strip 1', 'Merah Strip 1'), ('Merah Strip 2', 'Merah Strip 2')], default=None, max_length=100, verbose_name='Ke Sabuk')),
                ('hasilujian', models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default=None, max_length=100)),
                ('waktu', models.CharField(max_length=30)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_titles', to='zwinkle.Collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='krida_master_detail',
            name='krida_models',
        ),
        migrations.DeleteModel(
            name='Krida_model',
        ),
        migrations.DeleteModel(
            name='Krida_model_detail',
        ),
        migrations.DeleteModel(
            name='Krida_master',
        ),
        migrations.DeleteModel(
            name='Krida_master_detail',
        ),
    ]
