# Generated by Django 2.1 on 2019-01-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0014_auto_20190111_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('lulus', 'LULUS'), ('tidak lulus', 'TIDAK LULUS'), ('belum ujian', '-')], default=1, max_length=100),
        ),
    ]
