# Generated by Django 2.1 on 2019-01-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0015_auto_20190111_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('BELUM UJIAN', 'BELUM UJIAN')], default=1, max_length=100),
        ),
    ]
