# Generated by Django 2.1 on 2019-03-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0015_collection_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.FileField(null=True, upload_to='krida'),
        ),
    ]
