# Generated by Django 2.1 on 2019-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0016_auto_20190330_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='gambar',
            field=models.FileField(null=True, upload_to='krida'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
