# Generated by Django 2.1 on 2019-01-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0016_auto_20190111_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='krida_model',
            name='view',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default=1, max_length=100),
        ),
    ]
