# Generated by Django 2.1 on 2019-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0017_krida_model_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', 'BELUM UJIAN')], default=1, max_length=100),
        ),
    ]
