# Generated by Django 2.1 on 2019-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0018_auto_20190330_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='ujian',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=300),
        ),
        migrations.AlterField(
            model_name='collection',
            name='dojang',
            field=models.CharField(choices=[('Krida', 'Krida'), ('Bumi Putera', 'Bumi Putera'), ('Satria Muda', 'Satria Muda'), ('Black Eagle', 'Black Eagle'), ('Bangunharjo', 'Bangunharjo')], default='-', max_length=300),
        ),
    ]
