# Generated by Django 2.1 on 2019-03-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0019_auto_20190331_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default='-', max_length=100),
        ),
    ]
