# Generated by Django 2.1 on 2019-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0020_auto_20190331_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default='SEDANGUJIAN', max_length=100),
        ),
    ]
