# Generated by Django 2.1 on 2019-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0021_auto_20190401_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], max_length=100, null=True),
        ),
    ]
