# Generated by Django 2.1 on 2019-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0022_auto_20190401_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontitle',
            name='filter',
            field=models.CharField(choices=[('ON', 'ON')], max_length=100, null=True),
        ),
    ]
