# Generated by Django 2.1 on 2019-04-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0023_collectiontitle_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='filter',
            field=models.CharField(choices=[('ON', 'ON')], max_length=100),
        ),
    ]
