# Generated by Django 2.1 on 2019-04-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0024_auto_20190401_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiontitle',
            name='filter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
