# Generated by Django 2.1 on 2019-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0025_auto_20190112_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='model_pic',
        ),
    ]
