# Generated by Django 2.1 on 2019-04-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0025_auto_20190401_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='tampung_ujian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tampung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tampung', to='zwinkle.CollectionTitle')),
            ],
        ),
    ]
