# Generated by Django 2.1 on 2019-04-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0026_tampung_ujian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tampung_ujian',
            name='tampung',
        ),
        migrations.AlterModelOptions(
            name='collectiontitle',
            options={'get_latest_by': 'hasilujian'},
        ),
        migrations.DeleteModel(
            name='tampung_ujian',
        ),
    ]
