# Generated by Django 2.1 on 2019-04-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0027_auto_20190402_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectiontitle',
            name='filter',
        ),
    ]
