# Generated by Django 2.1 on 2019-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0028_remove_collectiontitle_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='ujian',
        ),
        migrations.AlterField(
            model_name='collectiontitle',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'Lulus'), ('TIDAK LULUS', 'Tidak Lulus'), ('AKAN UJIAN', 'Akan Ujian')], max_length=100, null=True),
        ),
    ]
