# Generated by Django 2.1 on 2019-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0029_auto_20190113_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
