# Generated by Django 2.1 on 2019-01-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0034_auto_20190113_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
    ]
