# Generated by Django 2.1 on 2019-01-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0035_auto_20190114_0650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='umur',
            field=models.IntegerField(),
        ),
    ]
