# Generated by Django 2.1 on 2019-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0037_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
