# Generated by Django 2.1 on 2019-01-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0041_auto_20190114_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.ImageField(default='images/vespa.jpg', upload_to='images'),
        ),
    ]
