# Generated by Django 2.1 on 2019-01-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0050_auto_20190114_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
