# Generated by Django 2.1 on 2019-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0052_auto_20190114_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='gambar',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
