# Generated by Django 2.1 on 2019-02-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0053_auto_20190114_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='view',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='OFF', max_length=100),
        ),
    ]
