# Generated by Django 2.1 on 2019-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0056_auto_20190213_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krida_model',
            name='hasilujian',
            field=models.CharField(choices=[('LULUS', 'LULUS'), ('TIDAK LULUS', 'TIDAK LULUS'), ('-', '-')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='pembayaran',
            field=models.CharField(choices=[('150.000', '150.000'), ('300.000', '300.000'), ('LUNAS', 'LUNAS')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='krida_model',
            name='view',
            field=models.CharField(choices=[('OFF', 'OFF'), ('ON', 'ON')], default='0', max_length=100),
        ),
    ]
