# Generated by Django 2.1 on 2019-02-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0059_auto_20190213_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='penulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zwinkle.krida_model'),
        ),
    ]
