# Generated by Django 2.1 on 2019-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwinkle', '0060_auto_20190213_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='penulis',
            field=models.CharField(max_length=100),
        ),
    ]
